# Generated by Django 2.1.4 on 2019-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='qwe@qwe.qwe', max_length=254),
            preserve_default=False,
        ),
    ]
