# Generated by Django 2.1.2 on 2019-01-25 09:56

from django.db import migrations, models
import newsletter.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('address', models.EmailField(max_length=254)),
                ('use_ssl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('activation_code', models.CharField(default=newsletter.helpers.createRandomString, max_length=64)),
                ('activated', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(default=newsletter.helpers.returnDateInFuture)),
                ('delete_code', models.CharField(default=newsletter.helpers.createRandomString, max_length=64)),
            ],
        ),
    ]
