# Generated by Django 2.1.2 on 2019-01-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailconfiguration',
            name='port',
        ),
        migrations.RemoveField(
            model_name='mailconfiguration',
            name='use_ssl',
        ),
    ]
