# Generated by Django 2.1.2 on 2019-01-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_mailconfiguration_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailConfiguration',
        ),
    ]
