# Generated by Django 2.1.2 on 2019-01-25 09:56

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required. Maximum 50 characters.', max_length=50)),
                ('tab_title', models.CharField(blank=True, help_text='Optional. Maximum 50 characters.', max_length=50, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color of the section page', max_length=7)),
                ('background_color_theme', models.CharField(default='#FFFFFF', help_text='Background color of the whole page', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('order_number', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ContentType')),
                ('home_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.HomePage')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.BooleanField(default=False)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(help_text='Maximum 1000 characters', max_length=1000)),
                ('deleted', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required. Maximum 50 characters.', max_length=50)),
                ('tab_title', models.CharField(blank=True, help_text='Optional. Maximum 50 characters.', max_length=50, null=True)),
                ('url', models.CharField(help_text="Required. Maximum 250 characters use only letter, numbers and '_' sign.", max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_url', message="Use only letters, numbers and '_' sign.", regex='^[a-zA-Z0-9_]{1,250}$')])),
                ('hidden', models.BooleanField(default=False, help_text='Should page be hidden for now.')),
                ('should_display', models.BooleanField(default=True, help_text='Optional. Should page be displayed.')),
                ('deleted', models.BooleanField(default=False, help_text='Should page be marked as deleted. Possible to undo in admin panel.')),
                ('order_number', models.IntegerField(default=0, help_text='Smaller number => More to the left. Sections sort ascending.')),
                ('restricted', models.BooleanField(default=False, help_text='Should page restricted for logged people.')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color of the section page', max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Section')),
            ],
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='customhtml',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout'),
        ),
    ]
