# Generated by Django 2.1.2 on 2019-01-16 08:24

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('title', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required. Maximum 50 characters.', max_length=50)),
                ('tab_title', models.CharField(blank=True, help_text='Optional. Maximum 50 characters.', max_length=50, null=True)),
                ('url', models.CharField(help_text="Required. Maximum 250 characters use only letter, numbers and '_' sign.", max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_url', message="Use only letters, numbers and '_' sign.", regex='^[a-zA-Z0-9_]{1,250}$')])),
                ('hidden', models.BooleanField(default=False, help_text='Should page be hidden for now.')),
                ('should_display', models.BooleanField(default=True, help_text='Optional. Should page be displayed.')),
                ('deleted', models.BooleanField(default=False, help_text='Should page be marked as deleted. Possible to undo in admin panel.')),
                ('order_number', models.IntegerField(default=0, help_text='Smaller number => More to the left. Sections sort ascending.')),
                ('restricted', models.BooleanField(default=False, help_text='Should page restricted for logged people.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Section')),
            ],
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='customhtml',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout'),
        ),
    ]
