# Generated by Django 2.1.2 on 2018-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181228_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_html',
            name='html',
            field=models.CharField(max_length=10000),
        ),
    ]
