# Generated by Django 2.1.2 on 2019-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_emailstemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstemplates',
            name='email_type',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailstemplates',
            name='helper_text',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
