# Generated by Django 2.1.4 on 2019-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190116_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
