# Generated by Django 2.1.2 on 2018-12-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181228_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=10000)),
                ('should_display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=10000)),
                ('should_display', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=10000)),
                ('should_display', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subsection')),
            ],
        ),
        migrations.RenameField(
            model_name='custom_html',
            old_name='slug',
            new_name='url',
        ),
    ]
