# Generated by Django 2.1.2 on 2019-01-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190128_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailsTemplates',
            new_name='EmailTemplate',
        ),
    ]
