# Generated by Django 2.1.2 on 2018-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181229_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='browser_title',
            field=models.CharField(default='Test title', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='browser_title',
            field=models.CharField(default='Test title', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsubsection',
            name='browser_title',
            field=models.CharField(default='Test title', max_length=50),
            preserve_default=False,
        ),
    ]
