# Generated by Django 2.1.2 on 2019-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190116_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='backgroud_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color of the section page', max_length=7),
        ),
    ]
