# Generated by Django 2.1.2 on 2019-01-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_section_backgroud_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='backgroud_color',
            new_name='background_color',
        ),
    ]
