# Generated by Django 2.1.2 on 2018-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181231_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubsection',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
