# Generated by Django 2.1.2 on 2019-01-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190117_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Should page be marked as deleted. Possible to undo in admin panel.'),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Should page be marked as deleted. Possible to undo in admin panel.'),
        ),
    ]
