# Generated by Django 2.1.2 on 2018-12-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181231_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubsection',
            name='ContentType',
        ),
        migrations.RemoveField(
            model_name='subsubsection',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Subsubsection',
        ),
    ]
