# Generated by Django 2.1.2 on 2018-12-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181231_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='ContentType',
            new_name='contentType',
        ),
        migrations.RenameField(
            model_name='subsection',
            old_name='ContentType',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='section',
            name='should_display',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='should_display',
        ),
        migrations.AlterField(
            model_name='subsection',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='url',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
