# Generated by Django 2.1.2 on 2019-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190118_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagelayout',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.CharField(help_text='Maximum 1000 characters', max_length=1000),
        ),
    ]
