# Generated by Django 2.1.2 on 2018-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181231_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='should_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
