# Generated by Django 2.1.2 on 2019-01-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190118_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required. Maximum 50 characters.', max_length=50)),
                ('tab_title', models.CharField(blank=True, help_text='Optional. Maximum 50 characters.', max_length=50, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color of the section page', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='pagelayout',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='home_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.HomePage'),
        ),
    ]
