# Generated by Django 2.1.2 on 2019-01-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190124_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_color_theme',
            field=models.CharField(default='#FFFFFF', help_text='Background color of the whole page', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagelayout',
            name='home_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.HomePage'),
        ),
    ]
