# Generated by Django 2.1.2 on 2019-01-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190102_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
