# Generated by Django 2.1.2 on 2019-01-02 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190102_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.CharField(help_text='Optional. Maximum 10000 characters.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='contentType',
            field=models.ForeignKey(help_text='Optional. How the page should be displayed.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContentType'),
        ),
        migrations.AlterField(
            model_name='section',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Should page be marked as deleted. Possible to undo in admin panel.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Should page be hidden for now.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order_number',
            field=models.IntegerField(default=0, help_text='Smaller number => More to the left. Sections sort ascending.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='should_display',
            field=models.BooleanField(default=True, help_text='Optional. Should page be displayed.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.CharField(help_text='Required. Maximum 250 characters use only letter and _.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_]{1,250}$')]),
        ),
    ]
