# Generated by Django 2.1.2 on 2019-01-02 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190102_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.CharField(help_text='Required. Maximum 250 characters use only letter and _.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_url', message='Use only letters and _ sign', regex='^[a-zA-Z_]{1,250}$')]),
        ),
    ]
