# Generated by Django 2.1.2 on 2019-01-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190102_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='contentType',
            field=models.ForeignKey(blank=True, help_text='Optional. How the page should be displayed.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContentType'),
        ),
    ]
