# Generated by Django 2.1.2 on 2019-01-02 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190102_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.CharField(help_text="Required. Maximum 250 characters use only letter, numbers and '_' sign.", max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_url', message="Use only letters, numbers and '_' sign.", regex='^[a-zA-Z0-9_]{1,250}$')]),
        ),
    ]
