# Generated by Django 2.1.2 on 2019-01-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190107_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tab_title',
            field=models.CharField(blank=True, help_text='Optional. Maximum 50 characters.', max_length=50, null=True),
        ),
    ]
