# Generated by Django 2.1.2 on 2019-01-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190107_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='parent',
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
    ]
