# Generated by Django 2.1.2 on 2019-01-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190107_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHTMl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Custom_HTML',
        ),
        migrations.DeleteModel(
            name='Subsection',
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContentType'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Section'),
        ),
        migrations.AddField(
            model_name='customhtml',
            name='page_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout'),
        ),
    ]
