# Generated by Django 2.1.2 on 2019-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190107_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhtml',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
