# Generated by Django 2.1.2 on 2019-01-15 09:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190115_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
