# Generated by Django 2.1.2 on 2019-01-15 10:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_section_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.PageLayout'),
            preserve_default=False,
        ),
    ]
