# Generated by Django 2.1.4 on 2019-01-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190115_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelayout',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ContentType'),
        ),
    ]
